package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Test avito")
    void generatedTest() {
        step("Open https://www.avito.ru/", () -> {
            step("// todo: just add selenium action");
        });

        step("nedvizhimost", () -> {
            step("// todo: just add selenium action");
        });

        step("nedvizhimost2", () -> {
            step("// todo: just add selenium action");
        });

        step("nedvizhimost3", () -> {
            step("// todo: just add selenium action");
        });

        step("nedvizhimost4", () -> {
            step("// todo: just add selenium action");
        });

        step("nedvizhimost5", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://www.avito.ru/'", () ->
            open("https://www.avito.ru/"));

        step("Page title should have text 'Доступ ограничен: проблема с IP'", () -> {
            String expectedTitle = "Доступ ограничен: проблема с IP";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://www.avito.ru/'", () ->
            open("https://www.avito.ru/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}